namespace ExportGenerator.Test;

internal static class VTableTestConst
{
	public const string SourceText =
	"""
    
    [ExportGenVTable]
    internal interface ITestV1
    {
        public int Version 
        {
            [ExportGenMethod("Version")]
            get; 
        }

        [ExportGenMethod("Test")]
        public void Test();
    }

    [ExportGenVTable]
    internal interface ITestV2
    {
        public int Version 
        {
            [ExportGenMethod("Version")]
            get; 
        }
    
        [ExportGenMethod("Test")]
        public void Test();

        public void Test2();
    }

    """;


	public static Dictionary<string, string> ExpectedDictFiles = new()
	{
		{
			"ITestV1_VTable.g.cs",
			"""
            // <auto-generated/>

            using System;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;

            public static partial class VTables
            {
            	[StructLayout(LayoutKind.Sequential, Pack = 8)]
            	public struct ITestV1_VTable
            	{
            		public nint Version;
            		public nint Test;
            	}

            }
            """
		},
		{
			"ITestV2_VTable.g.cs",
			"""
            // <auto-generated/>

            using System;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;

            public static partial class VTables
            {
            	[StructLayout(LayoutKind.Sequential, Pack = 8)]
            	public struct ITestV2_VTable
            	{
            		public nint Version;
            		public nint Test;
            		public nint Test2;
            	}

            }
            """
		},
	};
}
