using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ExportGenerator;

[Generator]
public class AttributesGenerator : IIncrementalGenerator
{
	private static readonly string AttributeSourceCode =
		"""
        // <auto-generated/>
        using System;
        using System.Runtime.InteropServices;

        /// <summary>
        /// Indicate the target should generate a dllexport entry point.
        /// </summary>
        /// <param name="exportBaseName">The base name to export this class.</param>
        /// <param name="exportPublicMethods">Whenever should export public methods or declare by ExportGenMethod.</param>
        /// <param name="useVTable">Whenever should create VTable for the target.</param>
        /// <param name="convention">The calling convention to use.</param>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
        public class ExportGen(string exportBaseName = "", bool exportPublicMethods = true, bool useVTable = true, CallingConvention convention = CallingConvention.Cdecl) : Attribute
        {
        	public string ExportBaseName { get; } = exportBaseName;
        	public bool ExportPublicMethods { get; } = exportPublicMethods;
            public bool UseVTable { get; } = useVTable;
            public CallingConvention Convention { get; } = convention;
        }

        /// <summary>
        /// Indicate the target has this method as constructor.
        /// </summary>
        /// <param name="exportName">The export name of this method.</param>
        /// <param name="convention">The calling convention to use.</param>
        /// <param name="includeBaseName">Should use the class base name with this class.</param>
        /// <remarks>
        /// ExportName and ExportBaseName will look like: ExportBaseName_ExportName.
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        public class ExportGenCreate(string exportName = "Create", CallingConvention convention = CallingConvention.Cdecl, bool includeBaseName = true, string exportBaseName = "") : ExportGenMethod(exportName, convention, includeBaseName)
        {
        	public string ExportBaseName { get; } = exportBaseName;
        }

        /// <summary>
        /// Indicate the target has this method as free (clearing the memory).
        /// </summary>
        /// <param name="exportName">The export name of this method.</param>
        /// <param name="convention">The calling convention to use.</param>
        /// <param name="includeBaseName">Should use the class base name with this class.</param>
        /// <remarks>
        /// ExportName and ExportBaseName will look like: ExportBaseName_ExportName.
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        public class ExportGenFree(string exportName = "Free", CallingConvention convention = CallingConvention.Cdecl, bool includeBaseName = true, string exportBaseName = "") : ExportGenMethod(exportName, convention, includeBaseName)
        {
        	public string ExportBaseName { get; } = exportBaseName;
        }

        /// <summary>
        /// Indicate the method should generate a dllexport entry point.
        /// </summary>
        /// <param name="exportName">The export name of this method.</param>
        /// <param name="convention">The calling convention to use.</param>
        /// <param name="includeBaseName">Should use the class base name with this class.</param>
        /// <remarks>
        /// ExportName and ExportBaseName will look like: ExportBaseName_ExportName.
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
        public class ExportGenMethod(string exportName, CallingConvention convention = CallingConvention.Cdecl, bool includeBaseName = true) : Attribute
        {
        	public string ExportName { get; } = exportName;
        	public CallingConvention Convention { get; } = convention;
        	public bool IncludeBaseName { get; } = includeBaseName;
        }

        /// <summary>
        /// Indicate the method should be ignored when generation happened.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        public class ExportGenIgnore() : Attribute;

        /// <summary>
        /// Indicate the target should generate a vtable.
        /// </summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
        public class ExportGenVTable(string exportBaseName = "") : Attribute
        {
        	public string ExportBaseName { get; } = exportBaseName;
        }

        /// <summary>
        /// Indicate the target should generate a vtable.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        public class ExportGenVTableCreate(string createMethodName = "") : Attribute
        {
        	public string CreateMethodName { get; } = createMethodName;
        }
        """;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
			ctx.AddSource("Attributes.g.cs", SourceText.From(AttributeSourceCode, Encoding.UTF8)
		));
	}
}
