using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace ExportGenerator;

[Generator]
public class ExportGenVTableGenerator : IIncrementalGenerator
{
	const string SourceCode =
			"""
			// <auto-generated/>

			using System;
			using System.Runtime.CompilerServices;
			using System.Runtime.InteropServices;

			public static partial class VTables
			{
			__BODY__
			}
			""";
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName("ExportGenVTable", Check, Transform).Where(x => x != null);
		context.RegisterSourceOutput(provider, CreateOuput);
	}

	private bool Check(SyntaxNode node, CancellationToken token)
	{
		return node is (ClassDeclarationSyntax or StructDeclarationSyntax or InterfaceDeclarationSyntax);
	}


	private Generated? Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
	{
		if (context.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
			return null;

		Generated generated = new()
		{
			Symbol = namedTypeSymbol,
			Methods = []
		};

		foreach (var method in namedTypeSymbol.GetMembers().OfType<IMethodSymbol>())
		{
			if (method == null)
				continue;

			if (method.HastAttribute("ExportGenIgnore"))
				continue;

			method.TryGetAttribute("ExportGenMethod", out AttributeData? attribute);

			generated.Methods.Add(new()
			{ 
				MethodSymbol = method,
				Attribute = attribute

			});
		}

		return generated;
	}

	private void CreateOuput(SourceProductionContext context, Generated? source)
	{
		if (source == null)
			return;

		StringBuilder sb = new();
		Helpers.GenerateVTable(source.Symbol, source.Methods, sb);
		string src = SourceCode.Replace("__BODY__", sb.ToString());

		context.AddSource($"{source.Symbol.Name}_vtable.g.cs", src);
	}

	public class Generated
	{
		public INamedTypeSymbol Symbol = null!;
		public List<MethodExport> Methods = [];
	}
}
