using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Runtime.InteropServices;
using System.Text;

namespace ExportGenerator;

[Generator]
public class ExportGenGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName("ExportGen", Check, Transform).Where(x => x != null);
		context.RegisterSourceOutput(provider, CreateOuput);
	}

	private bool Check(SyntaxNode node, CancellationToken token)
	{
		return node is ClassDeclarationSyntax or StructDeclarationSyntax;
	}

	private Generated? Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
	{
		if (context.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
			return null;

		if (!namedTypeSymbol.TryGetAttribute("ExportGen", out AttributeData? data) || data == null)
			return null;

		// All stuff from ExportGen attribute:
		string ExportBaseName = string.Empty;
		bool ExportPublicMethods = true;
		bool UseVTable = true;

		if (data.ConstructorArguments[0].Value is string _ExportBaseName)
			ExportBaseName = _ExportBaseName;

		if (data.ConstructorArguments[1].Value is bool _exportPublicMethods)
			ExportPublicMethods = _exportPublicMethods;

		if (data.ConstructorArguments[2].Value is bool _UseVTable)
			UseVTable = _UseVTable;

		Generated generated = new()
		{
			Symbol = namedTypeSymbol,
			ExportBaseName = ExportBaseName,
			UseVTable = UseVTable,
			MethodsToExport = []
		};

		foreach (var method in namedTypeSymbol.GetMembers().OfType<IMethodSymbol>().
			Where(m => 
				m != null &&
				!m.Name.StartsWith("EXPORT_") &&
				m.DeclaredAccessibility is Accessibility.Public &&
				!m.HastAttribute("ExportGenIgnore") &&
				m.MethodKind is not (MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.Constructor or MethodKind.SharedConstructor)
			))
		{
			// We check for special classes.
			if (method.HastAttribute("ExportGenCreate"))
			{
				generated.CustomCreate = method;
				continue;
			}

			if (method.HastAttribute("ExportGenFree"))
			{
				generated.CustomFree = method;
				continue;
			}

			if (method.HastAttribute("ExportGenVTableCreate"))
			{
				generated.CustomVTableCreator = method;
				continue;
			}

			bool hasGenMethod = method.TryGetAttribute("ExportGenMethod", out AttributeData? attribute);

			if (!ExportPublicMethods && !hasGenMethod)
				continue;

			generated.MethodsToExport.Add(new()
			{ 
				ExportGenAttribute = attribute,
				MethodSymbol = method,
			});
		}

		foreach (var interfaceSymbol in namedTypeSymbol.AllInterfaces)
		{
			bool useAllClass = interfaceSymbol.HastAttribute("ExportGenVTable");

			foreach (var method in interfaceSymbol.GetMembers().OfType<IMethodSymbol>().Where(m =>
				m != null &&
				!m.Name.StartsWith("EXPORT_") &&
				m.DeclaredAccessibility is Accessibility.Public &&
				!m.HastAttribute("ExportGenIgnore")
			))
			{
				if (!useAllClass)
				{
					if (!method.TryGetAttribute("ExportGenMethod", out _))
						continue;
				}

				ISymbol? implementationSymbol = namedTypeSymbol.FindImplementationForInterfaceMember(method);
				if (implementationSymbol is IMethodSymbol classMethodImplementation)
				{
					var m = generated.MethodsToExport.FirstOrDefault(x => SymbolEqualityComparer.Default.Equals(x.MethodSymbol, classMethodImplementation));
					classMethodImplementation.TryGetAttribute("ExportGenMethod", out AttributeData? attribute);
					if (m == null)
					{
						m = new()
						{
							MethodSymbol = classMethodImplementation,
							ExportGenAttribute = attribute
						};

						generated.MethodsToExport.Add(m);
						continue;
					}

					m.ExportGenAttribute ??= attribute;
				}
			}
		}

		return generated;
	}

	private void CreateOuput(SourceProductionContext context, Generated? source)
	{
		if (source == null)
			return;

		// report if vtable gen off and has no custom vtable creator!
		if (source.UseVTable == false && source.CustomVTableCreator == null)
		{
			context.ReportDiagnostic(Diagnostic.Create(Diagnostics.ExportGenVTableOffNoCustomVTable, null, [source.Symbol.Name]));
			return;
		}

		// Create autogen stuff
		StringBuilder sb = new();
		sb.AppendLine("""
			// <auto-generated/>

			using System;
			using System.Collections.Generic;
			using System.Collections.Concurrent;
			using System.Runtime.CompilerServices;
			using System.Runtime.InteropServices;

			""");

		// namespace if exists.
		string @namespace = Helpers.GetNameSpace(source.Symbol);
		if (!string.IsNullOrEmpty(@namespace))
			sb.AppendLine($"namespace {@namespace};");

		// this should always generate!
		sb.AppendLine(
					$$"""
					{{source.Symbol.DeclaredAccessibility.ToString().ToLower()}} partial {{(source.Symbol.IsValueType ? "struct" : "class")}} {{source.Symbol.Name}}
					{
						public const int GeneratedHash = {{Helpers.GetStableHashCode($"{Helpers.GetNameSpace(source.Symbol)}.{source.Symbol.Name}")}};
						private static readonly ConcurrentDictionary<IntPtr, {{source.Symbol.Name}}> PointerToCreatedClass = [];
					""");

		if (source.UseVTable)
		{
			sb.AppendLine("\tprivate static readonly nint[] FunctionPointers = new nint[(int)ExportCustomFunctions.MAX];");
			Helpers.GenerateVTable(source.Symbol, source.MethodsToExport, sb);
			var enums = GenerateEnum(@namespace, source.MethodsToExport, sb);
			GenerateStatic(context, source.ExportBaseName, @namespace, source.MethodsToExport, sb, enums, source.Symbol.Name);
		}

		foreach (var item in source.MethodsToExport)
		{

			if (item.MethodSymbol.MethodKind == MethodKind.ExplicitInterfaceImplementation && !item.MethodSymbol.TryGetAttribute("ExportGenMethod", out _))
			{
				context.ReportDiagnostic(Diagnostic.Create(Diagnostics.ExportMethodInterfaceImpNeedAttribute, item.MethodSymbol.Locations[0], [item.MethodSymbol.Name]));
				return;
			}

			new GenerateExportedClass(source.ExportBaseName, context, sb, item).Generate();
		}

		if (source.CustomCreate != null)
			new GenerateExportedClass(source.ExportBaseName, context, sb, source.CustomCreate).GenerateCreate(source.CustomVTableCreator);

		if (source.CustomFree != null)
			new GenerateExportedClass(source.ExportBaseName, context, sb, source.CustomFree).GenerateFree();


		sb.AppendLine("}");

		context.AddSource($"{source.Symbol.Name}_ExportGen.g.cs", sb.ToString());
	}

	public class Generated
	{
		public string ExportBaseName = string.Empty;
		public bool UseVTable = true;
		public INamedTypeSymbol Symbol = null!;
		public List<MethodExport> MethodsToExport = [];
		public IMethodSymbol? CustomCreate = null;
		public IMethodSymbol? CustomVTableCreator = null;
		public IMethodSymbol? CustomFree = null;
		public object? something = null;
	}

	public static List<string> GenerateEnum(string @namespace, List<MethodExport> methods, StringBuilder sb)
	{
		List<string> methodNames = [];
		methodNames.Clear();

		foreach (var method in methods)
		{
			string genMethodName = method.EnumName(@namespace);

			methodNames.Add(genMethodName);
		}

		sb.AppendLine(
					$$"""
						public enum ExportCustomFunctions
						{
					{{string.Join("\n",
						methodNames.Select(s => string.Format("\t\t{0},", s))
					)}}
							MAX
						}
					""");

		return methodNames;
	}

	public static void GenerateStatic(SourceProductionContext context, string ExportBaseName, string @namespace, List<MethodExport> methods, StringBuilder sb, List<string> enumNames, string name)
	{
		StringBuilder unsafeBuilder = new();

		foreach (var method in methods)
		{
			unsafeBuilder.Append($"\n\t\t\tFunctionPointers[(int)ExportCustomFunctions.{method.EnumName(@namespace)}] = (nint)(delegate* unmanaged ");
			var ex = new GenerateExportedClass(ExportBaseName, context, unsafeBuilder, method);
			ex.WriteCallConv();
			unsafeBuilder.Append("<");
			ex.WriteArgument();
			unsafeBuilder.Append(">)&");
			ex.WriteExportName(true);
			unsafeBuilder.Append(";");
		}


		string vtableFill = string.Empty;
		foreach (var item in enumNames)
		{
			vtableFill += $"\n\t\t\t{item} = FunctionPointers[(int)ExportCustomFunctions.{item}],";
		}


		sb.AppendLine(
					$$"""
						private static {{name}}_VTable _vtable;

						static {{name}}()
						{
							unsafe 
							{
						{{unsafeBuilder}}
							}

							_vtable = new()
							{
						{{vtableFill}}
							};
						}
					""");
	}
}
