using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;
using static ExportGenerator.ExportGenGenerator.Generated;

namespace ExportGenerator;

[Generator]
public class ExportGenGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName("ExportGen", Check, Transform).Where(x => x != null);
		context.RegisterSourceOutput(provider, CreateOuput);
	}

	private bool Check(SyntaxNode node, CancellationToken token)
	{
		return node is ClassDeclarationSyntax or StructDeclarationSyntax;
	}


	private Generated? Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
	{
		if (context.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
			return null;

		Generated generated = new()
		{
			Symbol = namedTypeSymbol,
			MethodsToExport = []
		};

		foreach (var method in namedTypeSymbol.GetMembers().OfType<IMethodSymbol>())
		{
			if (method == null)
				continue;

			if (method.Name.StartsWith("EXPORT_"))
				continue;

			if (method.DeclaredAccessibility is not Accessibility.Public)
				continue;

			if (method.TryGetAttribute("ExportGenIgnore", out _))
				continue;

			if (method.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet)
				continue;

			// we dont want contructors to be a creator class.
			if (method.MethodKind is MethodKind.Constructor or MethodKind.SharedConstructor)
				continue;

			// We check for special classes.
			if (method.HastAttribute("ExportGenCreate"))
			{
				generated.CustomCreate = method;
				continue;
			}

			if (method.HastAttribute("ExportGenFree"))
			{
				generated.CustomFree = method;
				continue;
			}

			if (method.HastAttribute("ExportGenVTableCreate"))
			{
				generated.CustomVTableCreator = method;
				continue;
			}

			method.TryGetAttribute("ExportGenMethod", out AttributeData? attribute);

			generated.MethodsToExport.Add(new()
			{ 
				Attribute = attribute,
				MethodSymbol = method,
			});
		}

		foreach (var interfaceSymbol in namedTypeSymbol.AllInterfaces)
		{
			bool useAllClass = interfaceSymbol.HastAttribute("ExportGenVTable");

			foreach (var method in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
			{
				if (method == null)
					continue;

				if (method.DeclaredAccessibility != Accessibility.Public)
					continue;

				if (method.HastAttribute("ExportGenIgnore"))
					continue;

				if (!useAllClass)
				{
					if (!method.TryGetAttribute("ExportGenMethod", out _))
						continue;
				}

				ISymbol? implementationSymbol = namedTypeSymbol.FindImplementationForInterfaceMember(method);
				if (implementationSymbol is IMethodSymbol classMethodImplementation)
				{
					var m = generated.MethodsToExport.FirstOrDefault(x => SymbolEqualityComparer.Default.Equals(x.MethodSymbol, classMethodImplementation));
					classMethodImplementation.TryGetAttribute("ExportGenMethod", out AttributeData? attribute);
					if (m == null)
					{
						m = new()
						{
							MethodSymbol = classMethodImplementation,
							Attribute = attribute
						};

						generated.MethodsToExport.Add(m);
						continue;
					}

					m.Attribute ??= attribute;
				}
			}
		}

		return generated;
	}

	private void CreateOuput(SourceProductionContext context, Generated? source)
	{
		if (source == null)
			return;

		foreach (var kv in source.MethodsToExport)
		{
			context.ReportDiagnostic(Diagnostic.Create(TEST, null, 
				source.Symbol.Name,
				kv.MethodSymbol.Name));
		}

		// Create Enums
		StringBuilder sb = new();
		sb.AppendLine("""
			// <auto-generated/>

			using System;
			using System.Collections.Generic;
			using System.Runtime.CompilerServices;
			using System.Runtime.InteropServices;

			""");

		string @namespace = Helpers.GetNameSpace(source.Symbol);
		if (!string.IsNullOrEmpty(@namespace))
		{
			sb.AppendLine($"namespace {@namespace};");
			sb.AppendLine();
		}

		sb.AppendLine(
					$$"""
					{{source.Symbol.DeclaredAccessibility.ToString().ToLower()}} partial {{(source.Symbol.IsValueType ? "struct" : "class")}} {{source.Symbol.Name}}
					{
						public const int GeneratedHash = {{Helpers.GetStableHashCode($"{Helpers.GetNameSpace(source.Symbol)}.{source.Symbol.Name}")}};

						private static readonly Dictionary<IntPtr, {{source.Symbol.Name}}> PointerToCreatedClass = [];
						private static readonly nint[] FunctionPointers = new nint[(int)ExportCustomFunctions.MAX];

					""");

		sb.AppendLine();
		Helpers.GenerateVTable(source.Symbol, source.MethodsToExport, sb);
		sb.AppendLine();
		GenerateEnum(@namespace, source.MethodsToExport, sb);

		sb.AppendLine("}");

		context.AddSource($"{source.Symbol.Name}_export_pre.g.cs", sb.ToString());


	}

	public class Generated
	{
		public INamedTypeSymbol Symbol = null!;
		public List<MethodExport> MethodsToExport = [];
		public IMethodSymbol? CustomCreate = null;
		public IMethodSymbol? CustomVTableCreator = null;
		public IMethodSymbol? CustomFree = null;
		public object? something = null;
	}

	public static void GenerateEnum(string @namespace, List<MethodExport> methods, StringBuilder sb)
	{
		List<string> methodNames = [];
		methodNames.Clear();

		foreach (var method in methods)
		{
			string genMethodName = method.MethodSymbol.Name;
			if (method.Attribute != null &&
				method.Attribute.ConstructorArguments[0].Value is string str &&
				!string.IsNullOrEmpty(str))
			{
				genMethodName = str;
			}

			if (genMethodName.Contains(@namespace + "."))
				genMethodName = genMethodName.Replace(@namespace + ".", string.Empty);

			if (genMethodName.Contains("."))
				genMethodName = genMethodName.Replace(".", "_");

			methodNames.Add(genMethodName);
		}

		sb.AppendLine(
					$$"""
						public enum ExportCustomFunctions
						{
					{{string.Join("\n",
						methodNames.Select(s => string.Format("\t\t{0},", s))
					)}}
							MAX
						}
					""");
	}

	const string Category = "AAAATEST";

	public static readonly DiagnosticDescriptor TEST = new(
		id: "EXGEN001",
		title: "test",
		messageFormat: "Object '{0}' method: '{1}' ({2})",
		category: Category,
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);
}
