using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ExportGenerator;

[Generator]
public class HelperClassGenerator : IIncrementalGenerator
{
	private static readonly string SourceCode =
		"""
		// <auto-generated/>
		using System;
		using System.Runtime.InteropServices;

		internal static class Helpers
		{
			/// <summary>
			/// Allocate <typeparamref name="T"/> and parse the structure to the pointer.
			/// </summary>
			/// <typeparam name="T">Any unmanaged type.</typeparam>
			/// <param name="unmanaged_t">The unmanaged object.</param>
			/// <returns>The pointer to the object.</returns>
			public static IntPtr ToIntPtr<T>(this T unmanaged_t) where T : unmanaged
			{
				IntPtr allocatedPointer = Marshal.AllocHGlobal(Marshal.SizeOf<T>());
				Marshal.StructureToPtr(unmanaged_t, allocatedPointer, false);
				return allocatedPointer;
			}
		}
		""";
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
			ctx.AddSource("Helpers.g.cs", SourceText.From(SourceCode, Encoding.UTF8)
		));
	}
}
