using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ExportGenerator;

[Generator]
public class StructsGenerator : IIncrementalGenerator
{
	private static readonly string StructsSourceCode = 
		"""
		// <auto-generated/>
		using System;
		using System.Runtime.InteropServices;

		/// <summary>
		/// Custom virtual table.
		/// </summary>
		[StructLayout(LayoutKind.Sequential, Pack = 8)]
		public struct CustomVTable
		{

		/// <summary>
		/// The pointer to the real vtable.
		/// </summary>
		public nint VTablePointer;

		/// <summary>
		/// Hash of the generated object.
		/// </summary>
		public int Hash;

		}
		""";
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
			ctx.AddSource("Structs.g.cs", SourceText.From(StructsSourceCode, Encoding.UTF8)
		));
	}
}
